INSERT INTO payment_details (payment_id,transaction_id,auth_status,amount,create_date) VALUES ('1','123','Success',45,toTimeStamp(toDate(now())));
INSERT INTO payment_details (payment_id,transaction_id,auth_status,amount,create_date) VALUES ('2','343','Failure',23, toTimeStamp(toDate(now())));
INSERT INTO payment_details (payment_id,transaction_id,auth_status,amount,create_date) VALUES ('3','643','Success',4, toTimeStamp(toDate(now())));
INSERT INTO payment_details (payment_id,transaction_id,auth_status,amount,create_date) VALUES ('4','326','Success',5, toTimeStamp(toDate(now())));
INSERT INTO payment_details (payment_id,transaction_id,auth_status,amount,create_date) VALUES ('5','123','Failure',12, toTimeStamp(toDate(now())));
